### ISSUE TITLE
Cannot run scripts other than :ApexInitProject before running this script

### ISSUE THREAD

**Issue by Lakshamana** [neowit/vim-force.com#100]
Using the latest version of this plugin as of March, 2021, with:
- Neovim v0.4.4
- tooling force.com v0.3.6.4
- Java version set as OpenJDK 11.0.2

I can't access any scripts other than :ApexInitProject, tho.
The only way to be able to run them is by actually running :ApexInitProject, then leaving blank all questions 'til the end of flow.

Steps to reproduce:
1. Writing 'Apex' and before pressing TAB to get neovim commands autocomplete
![image](https://user-images.githubusercontent.com/29443505/114418507-f4367800-9b88-11eb-91df-caae7188b50f.png)
2. Send TAB:
![image](https://user-images.githubusercontent.com/29443505/114418322-c8b38d80-9b88-11eb-823a-2a99c95f8f54.png)

That is, like it was the only available script on this plugin.

Steps to bypass the problem:
1. Run :ApexIniProject
![image](https://user-images.githubusercontent.com/29443505/114418784-3bbd0400-9b89-11eb-87b3-251ba20d7443.png)
2. Leave all the questions blank:
![image](https://user-images.githubusercontent.com/29443505/114419092-82126300-9b89-11eb-824f-4a25a722549a.png)
3. Get the fancy neovim autocompletion:
![image](https://user-images.githubusercontent.com/29443505/114419450-d1f12a00-9b89-11eb-8b6e-fb6663a76bb5.png)

Great plugin, btw!

**Comment by kgrzywacz** [comment]
As far as I remember the commands other than `ApexProjectInit` are loaded only after `ApexProjectInit` is run or an apex file is opened.

**Comment by neowit** [comment]
Hello  @Lakshamana, 
just to add some background to what @kgrzywacz explained above. 
With the exception of `ApexInitProject`  all other `:Apex...` commands are loaded only when specific file type is detected (opened) in vim, e.g. `.cls` or `.trigger` file. 
This is done to avoid waste of system resources when vim is opened for something other than SFDC project.  

FYI - `tooling force.com v0.3.6.4` is ancient and not 100% compatible with current `vim-force.com`. Consider upgrading to something more recent.

**Comment by Lakshamana** [comment]
Oh, sorry. So that was a misconception of how to use. Thank you, guys, for your directions! =)

**Comment by neowit** [comment]
@Lakshamana
AFAIK - `neovim` does not ship with vim `+job` feature which is required for  majority of async `vim-force.com` commands so it will most likely not work.
