### ISSUE TITLE
[Question] Is it possible to check what org am I currently using?

### ISSUE THREAD

**Issue by Lakshamana** [neowit/vim-force.com#101]
I was wondering if it is possible to know what org I'm using currently. By just running :ApexLogin, there's a "current" which advices me that somehow the plugin actually knows that. My point is: let the user know in a straightforward fashion
![image](https://user-images.githubusercontent.com/29443505/114783987-ecc1cb00-9d50-11eb-88aa-ee86d426834f.png)

I am not a big fan of Visual Studio Code, but I don't have much choice on my company by now. But, using ForceCode, one could easily say what company one's currently working on:
![image](https://user-images.githubusercontent.com/29443505/114784676-f3047700-9d51-11eb-94fe-6a738f6ca42f.png)

BTW, I'm using Vim now, just as your docs suggests =)

**Comment by Lakshamana** [comment]
Nevermind, I confused the concepts

**Comment by neowit** [comment]
Hello @Lakshamana 
When you execute any command requiring SFDC credentials vim plug-in looks (under `g:apex_properties_folder` for a `.properties` or `oauth2` file with the name matching your project name.

It is completely up to you how to name your projects but if you were to use some sort of naming convention then that might help you understand what client/environment is `current` just by looking at the path of the file you are currently editing.

For instance - if you were to name your projects something like: `<Client Name> (Sandbox Name)` then when looking at the apex file path which contains `.../Acme (dev2)/src/classes/MyClass.cls` you would know exactly where you are, i.e. sandbox `dev2` of client called `Acme`

**Comment by Lakshamana** [comment]
Thank you once more, @neowit. I am new to salesforce and your feedback really helped me)
