### ISSUE TITLE
Code Syntax Highlighting for files with extension `*.apxc`?

### ISSUE THREAD

**Issue by robjewell-ibotta** [neowit/vim-force.com#103]
Hello, thank you for this plugin. I have it installed successfully. However, whenever I create a file with `*.apxc` as the file extension the syntax highlighting doesn't work. Are there any plans to include syntax highlighting for these types of files?

FYI, I am completely new to salesforce development so apologies in advance if this is a silly question.

**Comment by neowit** [comment]
Hello @robjewell-ibotta 
If "*.apxc" is apex class then its extension must be in line with metadata API requirements, e.g. ".cls" 
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_classes.htm

If you want to create new apex class then use
`:ApexNewFile`
it will create apex class file with the appropriate extension.

There are no plans to handle file extensions (not supported by metadata api) in vim plug-in as we would have to rename each file (on the fly back and forth) before sending to Salesforce and after retrieving from salesforce.
