### ISSUE TITLE
Can't get syntax to show

### ISSUE THREAD

**Issue by westhechiang** [neowit/vim-force.com#42]
Hey there, I was SO overjoyed when I discovered that this existed. I got it to work for the most part but for some reason, syntax highlighting isn't working for me. I've followed your instructions and put the following in my .vimrc:

```set nocompatible```
```filetype plugin on```
```syntax on```

I'm on Vim 7.4 on a Mac.

I was curious if you know why this might be happening?

**Comment by westhechiang** [comment]
:ApexRefreshProject isn't working for me either. It's saying E492: Not an editor command: ApexRefreshProject

**Comment by neowit** [comment]
Hi @westhechiang 

If you open a Apex class in vim and run `:echo &filetype`, what do you see?
If it returns anything other than `apexcode` then you system did no load vim-force.com plugin

What does `:echo &runtimepath` return? Can you see the folder where you installed vim-force.com plugin?

**Comment by westhechiang** [comment]
Thanks for taking a look at this.

So when I type :echo &filetype, I get: st

When I type :echo &runtimepath, it returns a lot, I've underlined/bolded where i see vim-force.com <http://vim-force.com/> installed:
> /Users/wesleychiang/.vim,/Users/wesleychiang/.vim/bundle/ctrlp.vim,/Users/wesleychiang/.vim/bundle/emmet-vim,/Users/wesleychiang/.vim/bundle/loremipsum,/Users/wesleychiang/.vim/b
> undle/nerdcommenter,/Users/wesleychiang/.vim/bundle/nerdtree,/Users/wesleychiang/.vim/bundle/syntastic,/Users/wesleychiang/.vim/bundle/tabular,/Users/wesleychiang/.vim/bundle/ult
> isnips,/Users/wesleychiang/.vim/bundle/vim-airline,/Users/wesleychiang/.vim/bundle/vim-easymotion,/Users/wesleychiang/.vim/bundle/vim-force.com,/Users/wesleychiang/.vim/bundle/vi
> m-fugitive,/Users/wesleychiang/.vim/bundle/vim-javascript,/Users/wesleychiang/.vim/bundle/vim-multiple-cursors,/Users/wesleychiang/.vim/bundle/vim-repeat,/Users/wesleychiang/.vim
> /bundle/vim-session,/Users/wesleychiang/.vim/bundle/vim-surround,/Users/wesleychiang/.vim/bundle/vimforcebackup,/Users/wesleychiang/.vim/bundle/xml.vim,/usr/local/share/vim/vimfi
> les,/usr/local/share/vim/vim74,/usr/local/share/vim/vimfiles/after,/Users/wesleychiang/.vim/bundle/tabular/after,/Users/wesleychiang/.vim/bundle/ultisnips/after,/Users/wesleychia
> ng/.vim/after

Wes

**Comment by westhechiang** [comment]
Just got it to to work. I ended up going through your instructions line-by-line and the following lines of code was what fixed it:

```if has("unix")
		let &runtimepath=&runtimepath . ',~/vim/vim-force.com'
	elseif has("win32")
		let &runtimepath=&runtimepath . ',c:\Documents and Settings\username\vimfiles\vim-force.com'
	endif
	" make sure vim loads apexcode filetype detection
	runtime ftdetect/vim-force.com.vim```

**Comment by neowit** [comment]
Glad you managed to sort this out.

Looking at your runtimepath I'd say you must be using some sort of vim plugin manager.
The line which fixed it for you should not be needed if you used something simple and bulletproof like [pathogen](https://github.com/tpope/vim-pathogen).
What plugin manager do you use? I think the problem may be related to the fact that your plugin manager is overly "smart". Is this one of those plugins which supports delayed load?
