### ISSUE TITLE
Encoding issue with Anonymous block

### ISSUE THREAD

**Issue by RetekBacsi** [neowit/vim-force.com#44]
Hello,

java.nio.charset.UnmappableCharacterException is thrown when trying to execute anonymous block with certain special characters. (Deploy works correctly.)

Sample code:
String hashBase = 'árvíztűrő tükörfúrógép|ÁRVÍZTŰRŐ TÜKÖRFÚRÓGÉP';

Tooling version: 0.3.3.2, SFDC API version: 32.0
vim-force.com : commit 503baa97026a279704786b1c0b2fb763f78f6778

Regards,
 Gabor

**Comment by neowit** [comment]
Hello @RetekBacsi 

What OS is this? 
On OSX I can not reproduce the issue.

However, your error description gave me an idea of what it may be.
Can you check if [this build](https://dl.dropboxusercontent.com/u/266223/tooling-force.com-0.3.3.2-44.jar) works for you?

**Comment by RetekBacsi** [comment]
It's Windows 7.
The linked build fixed it. 

Thank you!

**Comment by neowit** [comment]
Hello @RetekBacsi

When you have a moment do you mind checking [this build](https://www.dropbox.com/s/htt8a7836rmzhyw/tooling-force.com-0.3.3.3.jar?dl=1), to see if it still works for you? 
Unlike the original test version in the comment above - this new build contains a more generic approach to the issue of encoding. If it still works for you then I will publish it as a release later.

Thanks.

**Comment by RetekBacsi** [comment]
Hello neowit,

Unfortunately the second build still throws UnmappableCharacterException.

Regards.

**Comment by neowit** [comment]
Thank you for checking.
What do you get if you run `:set fileencoding?` in vim on the file where you have this funny text which causes error?

**Comment by RetekBacsi** [comment]
fileencoding=utf-8

**Comment by neowit** [comment]
can you try [this version](https://www.dropbox.com/s/lbki9ysx3bqsx8i/tooling-force.com-0.3.3.3-44.2.jar?dl=0) please?
Make sure to check if you loaded the right version. 
`:ApexToolingVersion` should report "0.3.3.3-#44.2"

Thanks.

**Comment by RetekBacsi** [comment]
Sorry, I can't check this until wednesday. I'll get back then.

**Comment by RetekBacsi** [comment]
The 0.3.3.3-44.2.jar is identical to the 0.3.3.3 according to "diff" 
Also produces the same error, and reports 0.3.3.3 as version.

**Comment by neowit** [comment]
Sorry, my bad. Must have messed something up when prepared link to the file. Good that version info confirms that the file is not what I meant to share for testing.
Please can you check [this binary](https://www.dropbox.com/s/y4d0q0ydq7txj7u/tooling-force.com-0.3.3.3-44.3.jar?dl=1) instead.
This file should report version `0.3.3.3-#44.3`

**Comment by RetekBacsi** [comment]
This one works. 
(If apexlog could be utf-8 that'd be a dream, but this is more than enough for me.)

**Comment by neowit** [comment]
Great. Thanks for checking.

With regards to `:ApexLog` - I actually had a quick look into this before. If I remember correctly it appeared that Metadata deploy() call returns broken log text. if you call `:ExecuteAnonymous` (which does not use Metadata `deploy()`) then you get back correct log (with unicode stuff preserved), but commands like `:ApexDeploy` or `:ApexTest` have to use Metadata `deploy()` which returns text where unicode characters are already garbled.
Feel free to open another issue if you want to pursue this, maybe I will give it another look at some point, as broken unicode in deploy() log annoys me as well.

**Comment by RetekBacsi** [comment]
My experience was different - at least on win. The ExecuteAnonymous output was garbled, and reported latin-1 as encoding. 
I'm closing this one however, thank you for the help.
(And I won't open a ticket for the output encoding, that's not really an issue for me.)
