### ISSUE TITLE
How to debug "UNKNOWN EXCEPTION" on :ApexDeploy command?

### ISSUE THREAD

**Issue by chexxor** [neowit/vim-force.com#46]
I've looked at all the settings and properties of my installation and it looks like I'm not missing anything, but when I do `:ApexDeployOne deploy myorg`, I get a failure, which looks like it comes SFDC.

```
java.lang.Exception: UNKNOWN_EXCEPTION msg:UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1157353892-27489 (-824679420)
com.neowit.apex.Session.com$neowit$apex$Session$$waitDeploy(Session.scala:777)
com.neowit.apex.Session$$anonfun$18.apply(Session.scala:581)
com.neowit.apex.Session$$anonfun$18.apply(Session.scala:578)
com.neowit.apex.Session.withRetry(Session.scala:478)
com.neowit.apex.Session.deploy(Session.scala:578)
com.neowit.apex.actions.DeployModified.deploy(Deploy.scala:235)
com.neowit.apex.actions.DeployModified.deploy(Deploy.scala:168)
com.neowit.apex.actions.DeployModified.act(Deploy.scala:147)
com.neowit.apex.actions.Action$class.execute(Action.scala:83)
com.neowit.apex.actions.AsyncAction.execute(Action.scala:98)
com.neowit.apex.Executor.run(Runner.scala:106)
com.neowit.apex.Executor.execute(Runner.scala:44)
com.neowit.apex.Runner$.main(Runner.scala:30)
com.neowit.apex.Runner.main(Runner.scala)

RESULT=FAILURE
ERROR: {"text" : "UNKNOWN_EXCEPTION msg:UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1157353892-27489 (-824679420)"}
```

I love this Vim plugin you've made, so I really want to resolve this issue, but I don't know where to start. How can I see what is being sent to SFDC when I run this command? Where would you start when debugging this?

Also, when I click <enter> after seeing that message, I am given this message

```
".vim-force.com\response_deploySpecificFiles" [New File]
Cannot open file ".vim-force.com\response_deploySpecificFiles"
```

and I have to hit <enter> again to go back to my Apex file.

**Comment by nzchicken** [comment]
Have you set the following line to a valid path in your .vimrc?
`let g:apex_workspace_path="<your workspace path goes here>"`

The file you're referring to there is usually stored in the `.vim-force.com` folder under the project you are trying to deploy.

**Comment by neowit** [comment]
Hi @chexxor 

How many times have you run the a vim command with `UNKNOWN_EXCEPTION` result?
Did you give up after first attempt or you are getting this consistently?
The reason for this question is that SFDC sometimes returns this error for no apparent reason and if you execute exactly the same command again then it succeeds.

If you are getting this error every time then - as @nzchicken has already suggested - there is a good chance that you have not done configuration quite right. 
Please double check that you have configured all variables as specified in `:help force.com-settings`. 
You may also want to look at `:help force.com-config-example`.

If after that you are still having problems then please post here the full output of the command and not just the exception part. Specifically - what command line parameters are being sent to `tooling-force.com.jar`
The error details you posted above are from SFDC server and they are not very helpful to debug your local config issues. We need to see what happened before call to SFDC was sent.

**Comment by chexxor** [comment]
I've been trying different things, but still no success. I double-checked my vimrc file and the `:help force.com-settings`, and I'm pretty sure I've got everything I need in there.

It looks like I'm seeing a new error message. As for the previous error message, I was consistently getting that message. Seems it was an error on SFDC's side. Now, I'm getting an error which says `ERROR: {"text" : "The value following \"version\" in the XML declaration must be a quoted string."}`

I've done, `:echo g:apex_API_version`, and it shows the value I gave it in my vimrc file. I tried

    let g:apex_API_version=32.0
    let g:apex_API_version="32.0"
    let g:apex_API_version="'32.0'"

but they all give the same error.

Here's the command Vim generates:

```
C:\Windows\system32\cmd.exe /c (java  -Dorg.apache.commons.logging.simplelog.showlogname=false  -Dorg.apache.commons.logging.simplelog.showShortLogname=false  -Dorg.apache.commons.logging.simplelog.defaultlog=info  -jar ^"C:\tools\tooling-force.com-0.3.3.3.jar^" --action=deploySpecificFiles --tempFolderPath=^"c:\Temp\apex\temp^" --config=^"C:\Users\Alex\Work\ClearChannel_ProposalPlus\properties\deva.properties^" --projectPath=^"C:\Users\Alex\Work\deva^" --specificFiles=^"C:\Users\Alex\AppData\Local\Temp\VIAEE76.tmp-fileList.txt^" --responseFilePath=^"C:\Users\Alex\Work\deva\.vim-force.com\response_deploySpecificFiles^" --pollWaitMillis=1000 --maxPollRequests=1000)
```

Which "package.xml" file is it trying to read?

**Comment by neowit** [comment]
Hi @chexxor

The format of `g:apex_API_version`  is either
- `let g:apex_API_version = "32.0"` or 
- `let g:apex_API_version = 32.0`

FYI - you do not have to define this variable unless you want to create new files (with `:ApexNewFile`) using a specific version of API which does not match the one which plugin has by default. Right now it is v33.0

> Which "package.xml" file is it trying to read?

"C:\Users\Alex\Work\deva\src\package.xml"

If your package.xml is ok then you need to check *-meta.xml files you are trying to deploy. 
e.g. if you created a class MyClass.cls (using `:ApexNewFile`) while your `g:apex_API_version` had an invalid value then `MyClass-meta.xml` file of that class is most likely invalid.

**Comment by chexxor** [comment]
I was able to make some progress on this. I made a new directory, refreshed files from my sandbox org, then deployed them, all using this Vim plugin. Incredible! Nice work!

To explain the problem I had above: That project had invalid XML in the `src/package.xml` file. It uses the existing package.xml file? That's not what I'm used to. I use the grunt wrapper for the ant migration tool, which generates a fresh package.xml file in a temporary staging directory for each execution. It can do that because we created a JSON version of the package.xml file in that grunt plugin's config, which it uses to generate a package.xml file. (I'm not a fan of grunt, btw.)

I'm beginning to see that the `neowit/tooling-force.com` tool doesn't generate a package.xml file like that, correct? Rather, I'm expected to ensure the `src/package.xml` file always correctly reflects the contents of the `src` directory? I couldn't find any docs on your tool's policy of package.xml management. It think this topic is pretty important to have in the docs. Regardless, your tool is pretty dang sick-awesome. Seems to be better than anything else I've seen. :+1: 

About this original issue - I haven't seen the "UNKNOWN EXCEPTION" error since that day, so, I'll close this issue.

Hope having this issue open for so long hasn't put too much strain on your mind. I become disheartened easily lately, so it took awhile to find the will to come back and follow-up on this. :-/

**Comment by neowit** [comment]
Hello @chexxor 

Thanks for the feedback.

Yes package.xml is expected to be valid at all times. Same as if you were using Force.com IDE or Ant with ant-salesforce.jar.

package.xml does not have to reflect the actual local project structure (e.g. you may have retrieved CustomLabels.labels) using `:ApexRetrieve` but these do not have to be added to package.xml if you do not want them to be included in non file specific calls like `:ApexDeploy`.  
tooling-force.com does generate package xml (its Metadata API class version, not local file) based on circumstances, but in many cases it uses local package.xml as a base.

Normally the flow (if using vim-force.com plugin) is something like this:
You start with a generic custom package.xml (or generate one using `:ApexInitProject`) which may look like so
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>CustomLabels</name>
    </types>
    <types>
        <members>*</members>
        <name>Scontrol</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>19.0</version>
</Package>
```

then you do `:ApexRefreshProject` which will use your package.xml to get only resources you are interested in locally. e.g. above package.xml will not bring any custom object definitions on `:ApexRefreshProject` so you do not have to wait for irrelevant stuff to be downloaded.

FYI - while working with vim-force.com plugin you are not expected to modify package.xml by hand (except before initial refresh) or unless you know what you are doing.
If you are using tooling-force.com directly (for unattended/automated scenarios, e.g. CI ), then there are may be cases where you will use different versions of package.xml for different tasks. In those cases you have to make sure that you copy relevant package.xml into ./src dir as appropriate.
