### ISSUE TITLE
Save / refresh flow

### ISSUE THREAD

**Issue by kgrzywacz** [neowit/vim-force.com#51]
Hi,
I have problem with refreshing / saving flow.

Someone has saved file on the server, I would like to save this file from vim.

When I'm trying to save `ApexSave` file I get following error:
    
    Operation failed
    Outdated file(s) detected.`
    xxx.cls => Modified By: xxx; at: 2015-09-21T11:17:53.000Z; Local version saved at: 2015-09-18T10:50:25.000Z`
    Use 'refresh' before 'deploy'.
Then when i go with `ApexRefreshFile`
    
    Remote version is saved in: /home/xxx/force.com-projects/apex/vim-deployment/diffWithRemote/src
    No differences between local version and remote Org detected

After this, when i try to save with `ApexSave` I'm getting the same error as the first one.

What should to be able to save this file on the server?

**Comment by neowit** [comment]
When you run `:ApexRefreshProject` vim plugin will update local files and **also** local cache of file modification timestamps  from SFDC.
`:ApexRefreshFile` uses "diffWithRemote" in the background and only updates selected local file but does not touch local timestamp cache, hence vim plugin still considers local file as "outdated" (from SFDC LastModifiedDate point of view) even after `:ApexRefreshFile`.

In most cases you are supposed to use `:ApexRefreshProject` if you do not care what has changed on the remote, or `:ApexDiffWithRemoteFile` / `:ApexDiffWithRemoteProject` if you do care and want to resolve any conflicts manually.

Either way, if you did not use `:ApexRefreshProject` then after manual conflict resolution you can force save/deploy of a single file by using `:ApexSaveOne!` or `:ApexDeployOne!` (notice bang at the end of the command name), or if you want to save/deploy multiple files then use appropriate `:ApexSave<xxx>!` / `:ApexDeploy<xxx>!` commands.
Main thing to remember is that `!` at the end of Save/Deploy command name skips LastModifiedDate conflict check.

FYI - message `No differences between local version and remote Org detected` means that there are no real file (size/content) differences. Someone could have clicked Edit/Save on an Apex Class without any changes. This would update LastModifiedDate and hence plugin considers local file (with earlier LastModifiedDate) to be outdated.

**Comment by kgrzywacz** [comment]
@neowit Thank you for this response!

Would be nice if above information was available from help or/and in error message(about the <bang>. 
I found information about bang usage in *'g:apex_conflict_check'* help - I didn't search there before.

Also docs about ApexRefreshFile and ApexRefreshProject don't say much about differences between them.

Will this be ok if I update docs with information from your answer?

**Comment by neowit** [comment]
`:ApexRefreshFile` is kind of a half-baked command and really should work as you expected, as opposed to how it actually works. It was added as an adhoc request from some of more advanced users who have been using this plugin for years and know what they are doing. IMO `:ApexRefreshFile` encourages wrong workflow and should not be used at all. However for people who still find it useful a clearer documentation may be helpful. 
Any ideas/changes that improve documentation are always welcome.
