### ISSUE TITLE
Some questions / suggestions

### ISSUE THREAD

**Issue by kgrzywacz** [neowit/vim-force.com#53]
Hi @neowit ,

1. Is there a reason why Apex(Save/Deploy)One has additional confirmation like:
    ```
    Following files will be included
    foo/bar.cls
    Proceed? [y/N]
```
I would expect such message before saving multiple files(i.e. ApexSave), not when saving current file.

2. Would be nice to introduce some sort of command to load one of existing projects.
Right now we need to execute all commands with one of project's files opened.
For example, I usually switch constantly between: project files, ApexScrach file and todo file. 
It would be nice if I can execute ApexSave for my "loaded" project, without checking if my current buffer is one of the project's files.

3. Some example shortcuts proposed by you in doc will also benefit from 'loaded' project:

`nmap <leader>sc :noautocmd vimgrep /\<<C-R><C-W>\>/j PROJECTBASEPATH/**/*.cls PROJECTBASEPATH/**/*.trigger <CR>:cwin<CR>`

I'm a beginner vim & vim-force.com user and I'm not sure if it is possible to create such 'global' variable that could store loaded project path. So both points 2 & 3 may be impossible to do.

**Comment by neowit** [comment]
Hello @kgrzywacz 

1. Yes, there is a reason.   
if you have 2 or 3 splits open (when calling `:ApexSaveOne`) you may miss the fact that you are calling this command not for the buffer/file you intended. Hence there is a confirmation message.  
`:ApexSave` & `:ApexDeploy` pickup modified files automatically, so there is no need for user intervention.  

2. When you have files from multiple projects open in vim the "loaded" project will likely lead to accidental changes in the wrong project, so including this in the core plugin may not be a good idea for most advanced vim users.  
`:ApexSave` works from `ApexScratch` buffer, so from your example I understood that the only problem is that you cannot call Apex commands from your TODO file. Depending on your workflow there are may be different alternatives.
e.g. 
a. place your TODO.txt under src/ folder. If at least one loaded buffer has apex file in it then all `Apex` commands will be available from < project >/src/todo.txt file as well.  
b. I am sure you already know it, but just in case - if your TODO file is outside of src/ folder then (again, provided that your other buffer has Apex file open) you could switch to it with Ctrl+^ or any other buffer switching mechanism you prefer and call necessary command.  
I am sure there are dozens of other options available using standard vim functions.

3.  Yes, it is certainly possible. One option would be to do something like
```vim
let g:loaded_project="/path/to/project/root/here"
function! MySearch()
    let l:cwd = getcwd()
    " temporarily switch to "g:loaded_project" dir
    exe "cd ".fnameescape(expand(g:loaded_project)) 
    exe "noautocmd vimgrep /".expand("<cword>")."/j ./**/*.cls"
    " return to the original dir
    exe "cd ".fnameescape(l:cwd) 
    cwin
endfunction

nmap <leader>sc :call MySearch()<CR>
```
the above is the same as 
```vim
nmap <leader>sc :noautocmd vimgrep /\<<C-R><C-W>\>/j ../**/*.cls <CR>:cwin<CR>
```
with the exception that root folder for MySearch() is specified via `g:loaded_project`.  
`g:loaded_project` can be set from vim command line as required.  

There are other options to achieve similar results. vim is very customisable. Different users have different workflow, so there is no need to include simple things in the core plugin.

**Comment by neowit** [comment]
@kgrzywacz 
just a random thought on item 1. from your list - we could probably add a config variable to suppress "confirmation" prompt on `:ApexSaveOne` if you like to live dangerously and this confirmation annoys you enough so you could be bothered to set it in your .vimrc.

**Comment by kgrzywacz** [comment]
@neowit 
Thank you for your response.


1. I've already managed to surpass this with simple mapping:
`:nmap <leader>qs :w<CR>:ApexSaveOne<CR>y<CR>`
So no need for config variable. 
I just wondered if there is a reason for that confirmation, and it is, I just haven't thought about it(as I usually work without split).

2. Yes, you are right, it may cause some unwanted changes. 
I just came from Sublime and MM config and the need to open project's file in order to i.e. refresh project is a bit unnatural for me. I have to get used to that.

3. Thanks for code snippet!

**Comment by neowit** [comment]
regarding item 2 - vim supports file type plugins for a good reason - it does not make much sense to load `vim-force.com` when you (for instance) open a markdown file in vim. File type plugins (when properly done) is one of the reasons why vim takes so little to load, compared to some other text editors.  
Not sure what your workflow is but, if necessary, you can force `vim-force.com` plugin to load regardless. [Here are some options](http://stackoverflow.com/questions/1970544/how-to-manually-load-an-ftplugin-after-startup-in-vim). Filetype which you need to set is `apexcode`.  
Note syntax and filetype are different options, so if `set filetype=apexcode` breaks syntax highlighting in your current file, then you can also enforce syntax, e.g. `set syntax=xml`  

Alternatively you could just copy the command which `vim-force.com` generates for `tooling-force.com.jar` and map a shortcut to issue that command regardless of what file/project you are in.
