### ISSUE TITLE
Allow usage of tilde (~) for home directory usage

### ISSUE THREAD

**Issue by nzchicken** [neowit/vim-force.com#54]
This is a bit of a minor one, but would help none the less. From what I can see, I can't use tilde in the variables used to mark where the tooling jar, and other properties folders are.

This won't work:

    let g:apex_tooling_force_dot_com_path="~/.vim/tooling-force.com.jar"

This does:

    let g:apex_tooling_force_dot_com_path="/home/naylorb/.vim/tooling-force.com.jar"

I'm trying to standardise the development environments I'm using, and putting my vimrc into a github that I can just pull down when I want to set up my new environment. It just so happens that my work nix username isn't the same as my home one. Since everything is in my home dir, it just causes these minor issues. Is there a way to allow ~, or any other way that you know that can discover the home dir to avoid putting a explicit reference in my vimrc for this?

**Comment by chexxor** [comment]
This is a Vim problem rather than a vim-force.com problem.

You could create a variable which has what you want -
http://superuser.com/questions/119991/how-do-i-get-vim-home-directory

**Comment by nzchicken** [comment]
Ah, great, thanks for that.

For those that have the same issue, this is what the above now looks like (my .vimrc is in ~/.vimrc):

    let $VIMHOME=expand('<sfile>:p:h')
    let g:apex_tooling_force_dot_com_path="$VIMHOME/.vim/tooling-force.com.jar"

**Comment by chexxor** [comment]
Glad that worked for you! I didn't try it myself, so I was a bit worried. :-/
