### ISSUE TITLE
Request for syntax highlighting of soql date related keywords/functions

### ISSUE THREAD

**Issue by thomasdziedzic** [neowit/vim-force.com#55]
It would be nice if the following list of keywords were highlighted in soql blocks:
https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm

**Comment by neowit** [comment]
checkout [sqlKeywords](https://github.com/neowit/vim-force.com/tree/soqlKeywords) branch and see if added syntax highlighting it works for you.
Thanks.

**Comment by thomasdziedzic** [comment]
the branch works for me thanks!

**Comment by neowit** [comment]
Thank you for checking.
Merged into master.
