### ISSUE TITLE
Visualforce highlighting

### ISSUE THREAD

**Issue by kgrzywacz** [neowit/vim-force.com#56]
Hi @neowit,

Highlighting for apex stops after any digit in tag's name.

`<c:sometext1sometext>`
In above example only `c:sometext` will be highlighted properly.

It normally won't occur with standard Visualforce tags, but it may when using custom components.

Please see additional examples:
![image](https://cloud.githubusercontent.com/assets/11975837/10573007/5a5d3e6e-764d-11e5-9c3f-4b28e5e55a9b.png)
Edit: Actually, first example from above screenshot is invalid, as component name must begin with letter. 

Kamil

**Comment by neowit** [comment]
Hello @kgrzywacz thank you for reporting.
Check current version.
Does it solve the issue?

**Comment by kgrzywacz** [comment]
Hi @neowit,
Yes it solves it, thanks!

I found out that component may contain `_` (underscore) character. Underscore and everything following it aren't highlighted as well.

**Comment by neowit** [comment]
how about now?

**Comment by kgrzywacz** [comment]
It works, thanks!

**Comment by neowit** [comment]
if everything works let's close it then.
