### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by kendagriff** [neowit/vim-force.com#58]
Quickly saying thank you for this project. I've used it for over a year now, and it's become an important part of my workflow.

Thanks again!

**Comment by nzchicken** [comment]
I'm want to second this. I've been using vim-force for almost 2 years now (started on windows, now on ubuntu), and I'm amazed that a free tool continues to get updates, and continues to get better and better. If only I could convince more people to use vim....

**Comment by neowit** [comment]
Thank you guys!

By the way - do not hesitate to send feature and/or pull requests. No promises that any of them will be implemented, but if you do not ask then chances to get a feature you want are even less.

You might have noticed that the project has not seen updates for a while. I have not abandoned it yet. Have not been working much on SFDC side of things in the last few months, which led to lack of new ideas for the plugin.

**Comment by chexxor** [comment]
Truth! You're a great project owner, @neowit. Thanks for sharing!

**Comment by michaelbruce** [comment]
I use tooling-force everyday, thanks for creating this project.
