### ISSUE TITLE
Enable apex* commands on package.xml file

### ISSUE THREAD

**Issue by nzchicken** [neowit/vim-force.com#59]
A bit of a fringe case, but is there an easy way to include the ability to use ApexRefreshProject from a package.xml file? Would make life a lot easier to pull down a new component from editing the package.xml directly.

And I suppose this leads into another question of whether there should be some kind of metadata selector menu. I'm thinking NERD tree styling, and possibly similar to how eclipse manages it. I can imagine it being quite a bit of work though.

**Comment by neowit** [comment]
use ApexRefreshProject from a package.xml file
If your `package.xml` is under `src/` folder (as it normally is) then this should work out of the box, see:
https://github.com/neowit/vim-force.com/blob/master/ftdetect/vim-force.com.vim#L28

    some kind of metadata selector menu
Once you open any file (including package.xml) which `vim-force.com` plugin detects as part of apex project you can call `:ApexRetrieve` and select relevant metadata types. Once retrieval is complete plugin asks whether you want to update `package.xml` with selected types or not.

**Comment by nzchicken** [comment]
See, this is why I need to update my extensions more often (yes I know it's been a while since these were implemented hah).

Thanks again for the awesome work!
