### ISSUE TITLE
Test Suites

### ISSUE THREAD

**Issue by b-n** [neowit/vim-force.com#60]
[Test Suites](https://releasenotes.docs.salesforce.com/en-us/spring16/release-notes/rn_apex_tests.htm#rn_apex_tests_test_suites) were just launched in Spring 16. Some support for them would be super helpful.

Usecase: I have a particular feature that I want to run a set of tests on to check the coverage for my feature.

It looks like the test suites are stored in new `ApexTestSuite` and `TestSuiteMembership` objects, so maybe a query to that, and a run all tests on it? I'm not sure what they'll be adding to the API to support this directly. With some luck you can just call a the ApexTestSuite as part of the tooling API for testing.

**Comment by nzchicken** [comment]
And just as I post that, I read this

> You can now pass ApexTestSuite IDs to the runTestsAsynchronous() SOAP call

So maybe a facility to query the nice name, and call the test. Ideally an easy way to create a Test Suite using Vim menus, etc, would be an added bonus

**Comment by neowit** [comment]
Hello @nzchicken 
Good idea.
Do you have any suggestions regarding vim/ui side of this ? In terms of user experience.

**Comment by nzchicken** [comment]
For me, something like `:ApexTestSuite <name of suite>` (where name of suite is tab completable) would make sense to get to the edit menu. The edit menu I feel should be similar to the `:ApexRetrieve` functionality, giving a users the ability to toggle on and off tests from the suite.

In addition to this, it would be nice if ApexTest could tab complete the suites aswell. In this case, making the query to the server every time you want to tab complete could take too long, so I would say a fair compromise would be to pull down all tests with either a seperate command, or on `:ApexRefreshProject`.

**Comment by neowit** [comment]
Makes sense.
Thank you for the suggestions.

**Comment by b-n** [comment]
Just doing some house keeping and cleaning up old issues I created where I didn't follow though. Thanks though!
