### ISSUE TITLE
Storing of username, password, token

### ISSUE THREAD

**Issue by kgrzywacz** [neowit/vim-force.com#64]
Hi @neowit ,

Do you know any way of storing you username, password and token in a safe way - as far as I know currently it must be saved in plain text file on the hard drive which may be a little bit risky.

Have you considered using oauth in vim-force.com / tooling-force.com ?

Thanks,
Kamil

**Comment by neowit** [comment]
Hello @kgrzywacz ,

> Do you know any way of storing you username, password and token in a safe way

There are plenty of options.
Full drive encryption, folder encryption, container like Truecrypt (which is mentioned in the documentation - see `:help 'g:apex_properties_folder'`), etc.

Oauth token also has to be stored locally. 
Password (stored in .properties file) is just as accessible as Oauth token stored in some other file.
