### ISSUE TITLE
TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.","errorCode":"UNSUPPORTED_CLIENT

### ISSUE THREAD

**Issue by dudunato** [neowit/vim-force.com#65]
Is anyone facing this same problem?

**Comment by neowit** [comment]
If you did not have this error before and suddenly started to get it then "Require TLS 1.1 or higher for HTTPS connections" most likely has been activated in your SFDC Org.
http://help.salesforce.com/HTViewSolution?id=000232847&language=en_US

Either way this should be a non issue for current version of [tooling-force.com.jar](https://github.com/neowit/tooling-force.com).

Which Java and tooling-force.com.jar versions you use?
You may want to review [System Requirements](https://github.com/neowit/tooling-force.com#system-requirements) for tooling-force.com.jar and update the jar itself if you are on a very old version.

**Comment by dudunato** [comment]
Now I’m using 0.3.6.2. I saw this note and then I changed the .jar and I still get the error. :/

Maybe I need to setup a env variable to tell the tooling.jar what TLS it should use?

-- 
@dudunato

On 28 de junho de 2016 at 12:17:09, Andrey Gavrikov (notifications@github.com) wrote:

If you did not have this error before and suddenly started to get it then "Require TLS 1.1 or higher for HTTPS connections" most likely has been activated in your SFDC Org.
http://help.salesforce.com/HTViewSolution?id=000232847&language=en_US

Either way this should be a non issue for current version of tooling-force.com.jar.

Which Java and tooling-force.com.jar versions you use?
You may want to review System Requirements for tooling-force.com.jar and update the jar itself if you are on a very old version.

**Comment by neowit** [comment]
tooling-force.com.jar itself does not have any logic for TLS. TLS is supported by Java/JVM.
Are you sure you are running Java 8?

**Comment by chexxor** [comment]
We use a Ruby tool to deploy to our org using Metadata API. For that, Ruby shells out to OpenSSL (or uses its lib), so we needed to ensure we had newer than OpenSSL v1.0.1. Also, anything earlier than Ruby 2.0.0 doesn't support requesting newer than TLSv1.0, so we also had to ensure we were using Ruby 2.0.0.

Java libs, on the other hand, implement TLS on their own - they don't shell out to OpenSSL. I think it's a "sockets" lib in Java. I'm guessing the version of this lib matters. I'm guessing, also, that the default TLS version requested of that lib by the JVM matters, which is why a specific JVM version is mentioned.

**Comment by neowit** [comment]
Hello @dudunato,

In addition to checking Java version can you also mention what JVM you use - is it Oracle one or something else?

Also, is it safe to assume you have only 1 java version installed and there is no chance that `tooling-force.com.jar` is executed with something other than Java 8 ?

**Comment by alex-shekhter** [comment]
For Java 1.7 add the following line to the .vimrc:

let g:apex_java_cmd="java -Dhttps.protocols=TLSv1.1,TLSv1.2 "

Works here :)

**Comment by dudunato** [comment]
Worked great. Thanks guys!
