### ISSUE TITLE
Unable to run any commands

### ISSUE THREAD

**Issue by anandghegde** [neowit/vim-force.com#72]
Sometimes I keep getting this error on any of the commands like ApexDeploy or ApexRefreshProject
```

  --action=saveModified --tempFolderPath='/Users/ahegde/.vim_runtime/sources_non_forked/force_config_folder/temp_folder' --config='/Users/ahegde/.vim_runtime/sources_non_forked/force_config_folder/properties_folder/sfdcaug.properties' --projectPath='/Users/ahegde/releases/sfdcaug' --ignoreConflicts=true --responseFilePath='/Users/ahegde/releases/sfdcaug/.vim-force.com/response_saveModified' --pollWaitMillis=1000 --maxPollRequests=1000
 Trying to start server using command: java  -Dorg.apache.commons.logging.simplelog.defaultlog=debug -Dfile.encoding=UTF-8  -jar /Users/ahegde/.vim_runtime/sources_non_forked/force_config_folder/tooling-force.jar --action=serverStart --port=8888 --timeoutSec=1200
 [DEBUG] UsageReporter - java.lang.NullPointerException
************************************
 press 'q' to close this buffer
************************************
```

This is happening only on this project. On another project the commands are working fine. I checked the credential file and it seems fine.

**Comment by neowit** [comment]
Hello @anandghegde ,

Please try [this version](https://www.dropbox.com/s/4eh6r7agyuyfzmf/tooling-force.com-0.3.6.4-72.jar?dl=1) (with debug enabled, as you did in your example above) and send me the result.
You will still get the same issue, but "ApexMessages" output should include some stack trace which may help to pinpoint the problem.
If stack trace is not returned - check `:ApexToolingVersion`, it should report "version: 0.3.6.5-#72".

**Comment by neowit** [comment]
closed due to inactivity
