### ISSUE TITLE
Key not present in Dictionary: isSilent

### ISSUE THREAD

**Issue by zefreak** [neowit/vim-force.com#73]
I keep getting this error when trying to run a command. It flashes on the screen a few times (never for long enough to really read it) and then vim will exit with Aborted or a seg fault.

line 7:
E716: Key not present in Dictionary: isSilent
E15: Invalid expression: !self.isSilent
line 10:
E716: Key not present in Dictionary: isSilent && len(l:msg) > 0
E15: Invalid expression: !self.isSilent && len(l:msg) > 0

Edit: I seem to be able to run :ApexDeployOne successfully, but others dont work

**Comment by neowit** [comment]
Hello @zefreak 

You may want to try latest vim version. I have seen seg fault issues on early versions of jobs support implemented in vim/gvim/macvim.

If that does not work please post output of `:version` and your OS version here.

**Comment by zefreak** [comment]
I updated vim to 8.0 and it seems to have resolved the issue. I am running Ubuntu 16.04 in case anyone else has issues. 

Thanks for the quick response
