### ISSUE TITLE
Project Refresh error

### ISSUE THREAD

**Issue by zefreak** [neowit/vim-force.com#74]
When running ApexRefreshProject, I am getting 'NoSuchElementException: key not found: unpackaged/reports/Sample_Reports

Is there a known resolution for this?

**Comment by neowit** [comment]
- What version of `tooling-force.com.jar` you use?
-- you can check that with `:ApexToolingVersion` in vim
- what API version is in your `package.xml` ?
- what happens if you remove reports from `package.xml` and refresh without them ?

**Comment by zefreak** [comment]
tooling-force.com.jar version is 0.3.6.6 
SFDC API Version is 36.0

if I remove reports, i get the same error but for documents:
'NoSuchElementException: key not found: unpackaged/documents/SalesTools

**Comment by neowit** [comment]
> SFDC API Version is 36.0

is this API version reported by tooling-force.com.jar or the one from your `package.xml` ?

**Comment by zefreak** [comment]
It was reported by tooling-force.com.jar but it is also what I have in the package.xml

**Comment by zefreak** [comment]
I tried it on a new project (different client) and it seems to be working, it must be something project related.

**Comment by neowit** [comment]
Can you post full `package.xml` here? From the project where you get the error.

**Comment by zefreak** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>*</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexTrigger</name>
	</types>
	<types>
		<members>abc</members>
		<name>CustomApplication</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomLabels</name>
	</types>
	<types>
		<members>Account</members>
		<members>AccountContactRole</members>
		<members>Activity</members>
		<members>Announcement__c</members>
		<members>Asset</members>
		<members>AssistantProgress</members>
		<members>Call_Center_Agent__c</members>
		<members>Campaign</members>
		<members>CampaignMember</members>
		<members>Case</members>
		<members>CaseContactRole</members>
		<members>Contact</members>
		<members>ContentVersion</members>
		<members>Contract</members>
		<members>ContractContactRole</members>
		<members>DuplicateRecordItem</members>
		<members>DuplicateRecordSet</members>
		<members>EmailMessage</members>
		<members>Event</members>
		<members>ExchangeUserMapping</members>
		<members>FeedItem</members>
		<members>Idea</members>
		<members>Lead</members>
		<members>Macro</members>
		<members>MacroAction</members>
		<members>MacroInstruction</members>
		<members>Opportunity</members>
		<members>OpportunityCompetitor</members>
		<members>OpportunityContactRole</members>
		<members>OpportunityLineItem</members>
		<members>OpportunityTeamMember</members>
		<members>PartnerRole</members>
		<members>Plan__c</members>
		<members>Pricebook2</members>
		<members>PricebookEntry</members>
		<members>Product2</members>
		<members>Reserve_Event__c</members>
		<members>Reserve_Location__c</members>
		<members>Reserve_Request__c</members>
		<members>Reserve_Schedule__c</members>
		<members>SFGA__Ad_Group__c</members>
		<members>SFGA__Google_Campaign__c</members>
		<members>SFGA__Keyword__c</members>
		<members>SFGA__Search_Phrase__c</members>
		<members>SFGA__Text_Ad__c</members>
		<members>SFGA__Version_33_0_3__c</members>
		<members>Sales_Plan__c</members>
		<members>Site</members>
		<members>SocialPersona</members>
		<members>SocialPost</members>
		<members>Solution</members>
		<members>StreamingChannel</members>
		<members>Sync__c</members>
		<members>Task</members>
		<members>User</members>
		<members>UserProvisioningRequest</members>
		<members>abc__c</members>
		<members>dsfs__DocuSignAccountConfiguration__c</members>
		<members>dsfs__DocuSign_Envelope_Document__c</members>
		<members>dsfs__DocuSign_Envelope_Recipient__c</members>
		<members>dsfs__DocuSign_Envelope__c</members>
		<members>dsfs__DocuSign_Recipient_Status__c</members>
		<members>dsfs__DocuSign_Status__c</members>
		<name>CustomObject</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomTab</name>
	</types>
	<types>
		<members>SalesTools</members>
		<members>SharedDocuments</members>
		<name>Document</name>
	</types>
	<types>
		<members>abc_Email_Templates</members>
		<members>asd_Email_Templates</members>
		<members>Sales_Email_Templates</members>
		<name>EmailTemplate</name>
	</types>
	<types>
		<members>*</members>
		<name>Layout</name>
	</types>
	<types>
		<members>*</members>
		<name>PermissionSet</name>
	</types>
	<types>
		<members>*</members>
		<name>Profile</name>
	</types>
	<types>
		<members>*</members>
		<name>StaticResource</name>
	</types>
	<types>
		<members>*</members>
		<name>Workflow</name>
	</types>
	<version>36.0</version>
</Package>

**Comment by neowit** [comment]
Thanks.
I was hoping to be able to reproduce the issue with your `package.xml`, no such luck unfortunately.

> I am getting 'NoSuchElementException: key not found: 

Presumably this is the whole error? There is no stack trace available?
If there is no stack trace then without being able to reproduce the problem not sure what else can be done...
