### ISSUE TITLE
ApexCompare command always returns comparison cancelled

### ISSUE THREAD

**Issue by noenthu** [neowit/vim-force.com#75]
:ApexCompare always returns comparison cancelled.

:ApexToolingVersion returns
INFO: tooling-force.com - version: 0.3.6.6; SFDC API Version: 36.0

looks like this won't work on non gui versions of vim :echo has("browse") returns 0

Anyway for this to be handled by passing the arguments manually? current file vs file to compare against

**Comment by neowit** [comment]
FYI - `:ApexCompare...` commands do not use tooling-force.com.jar as they are meant to compare **local** files. If you mean to compare local files with their remote counterparts in SFDC then use `:ApexDiff...` commands.

If you use vim version which does not have `+browse` then, according to vim help `:h browsedir(`
> On systems where a directory browser is not supported a file browser is used  

if this also does not work for your version of vim then you could use one of vim's `diff...` commands, e.g. `:diffsplit filename`. 
`:ApexCompare` is nothing more than just a convenience shortcut to select a file to compare with and launch user defined comparison tool. If you want to pass file names manually then consider using one of standard vim `:diff...` commands or use your diff tool of choice directly.

**Comment by noenthu** [comment]
Thanks for the response. I think the non gui version of vim I have does not support File Browsing using browse/browsedir I'll look into using vimdiff
