### ISSUE TITLE
No apex/SOQL completion in vim-force.com-scratch.txt

### ISSUE THREAD

**Issue by noenthu** [neowit/vim-force.com#76]
Apex/SOQL completion returns SUCCESS in the response_listCompletions but no results are shown when using it within the :ApexScratch or directly in src/vim-force.com-scratch.txt file

**Comment by neowit** [comment]
`SUCCESS` means there was not errors. It has no bearing on whether any completions could be found or not.
Code completion is based on apex code parser, if file is very broken (apex code syntax wise), or does not look like an apex class at all, then parser will fail.
If you want code completion in scratch buffer (:ApexScratch) then it needs to look like a reasonably valid apex class. For instance

```
/* This is a scratch file */
class ScratchFileClass {

    String str;
    str.<invoke completion here>

}
```
if that does not work then check `:set ft?` it is expected to return `filetype=apexcode`

Main purpose of `:ApexScratch` is to have some (easily accessible, project specific) place to store snippets of code, e.g. pieces which can be visually selected and executed via `:ApexExecuteAnonymous` or `:ApexQuery`. It was not designed to support completion, but if you really want completion then you can have it with the method mentioned above.

**Comment by noenthu** [comment]
Tried what you recommended and still not seeing completions in the scratch file

![output](https://cloud.githubusercontent.com/assets/989601/21743588/ec14fcd4-d4ca-11e6-8745-6279ddbb948c.gif)

**Comment by neowit** [comment]
Can you confirm following

1. You are using current/latest version of `vim-force.com` plugin and `tooling-force.com.jar` ?

2. On the frame where you show vim-force.com-scratch.txt buffer are we seeing **complete** file content? There is nothing on the page above which makes this a not valid apex class file?
Just for the sake of a test - can you try making sure that those 4 example lines are the only code in this buffer ?
```
class ScratchFileClass {
    String str;
    str.<invoke completion here>
}
```

3. Does completion work for you in normal apex class files?

4. Do you use some kind of intermediate/additional plugin to invoke completion?
If yes, have you tried disabling it and calling completion directly via standard `Ctr-X-O` ?

5. What do you get when call `:set omnifunc?` in vim-force.com-scratch.txt buffer ?

**Comment by noenthu** [comment]
I tried by commenting out all the lines of code in the scratch file and that allowed it to work.

I was under the wrong impression that the code completion would work even outside the declaration of a class. Seems to be working perfectly fine if that is the expected behavior

![output](https://cloud.githubusercontent.com/assets/989601/21745692/98c143a4-d4f6-11e6-93f2-5c9b80d61e66.gif)

**Comment by noenthu** [comment]
Before I close the issue - Just wanted a quick clarification. Any benefit in enabling autocomplete to work outside of the context of a class definition?

**Comment by neowit** [comment]
Autocomplete provided by `tooling-force.com.jar` is based on [Apexcode](https://github.com/neowit/tooling-force.com/blob/master/src/main/java/Apexcode.g4) grammar.
The grammar's entry point is Class or Interface declaration. Outside of Class or Interface there is no starting point and hence AST can not be built.

In other words - apex autocomplete is not supported outside of class/interface definition and there is no option to "enable" it.

**Comment by noenthu** [comment]
Thanks for the clarification
