### ISSUE TITLE
ApexTest do not works

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neowit/vim-force.com#80]
`:ApexTest MyTest`
return
`Please specify test(s) to run or * to run all unpackaged tests in the Org`

**Comment by nzchicken** [comment]
`:ApexTest` requires 2 parameters.

First Parameter = `tooling-sync` or `tooling-async` or `metadata-testAndDeploy` or `metadata-checkOnly`
Second Parameter = Your Apex class name

Try this: `:ApexTest tooling-sync MyTest` assuming MyTest has been deployed to your org.

Check out `:help ApexTest` for more information.

**Comment by vitaly-zdanevich** [comment]
Sorry, now it works - but you can update `Please specify test(s) to run or * to run all unpackaged tests in the Org`

to something like

`Incorrect command, format is :ApexTest [tooling-sync|tooling-async|metadata-testAndDeploy|metadata-checkOnly] [MyTestName]`
