### ISSUE TITLE
:ApexExecuteAnonymous: show some error for ~100 milliseconds

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neowit/vim-force.com#84]
Not enough time to read what is wrong with selected code :(

**Comment by neowit** [comment]
`:help ApexMessages`
`:help messages`

**Comment by vitaly-zdanevich** [comment]
But this looks like incorrect default behaviour...

**Comment by neowit** [comment]
"correct" default behaviour is a matter of opinions.

Closing as this is turning to a forum discussion.
If you have concrete suggestions about better default behaviour and can provide supporting arguments feel free to re-open.
