### ISSUE TITLE
ApexTestWithCoverage open buffer with incorrect data

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neowit/vim-force.com#85]
In buffer `apex_messages` among other info I see that my class have 118 lines but in reality it has 449 lines, also report says that covered 12% but `:ApexTestCoverageShow` highlight more that 90% of the file.

**Comment by neowit** [comment]
Thank you for your message.

Issue description does not provide much useful information to reproduce the problem so I am not sure what you expected when posted it.

FYI - buffer `apex_messages` displays data returned by Salesforce. So if line count is wrong then this is probably what SFDC returned. We can not be sure without some way of reproducing the problem though.

**Comment by vitaly-zdanevich** [comment]
ok, sorry to interrupting and thank you for that plugin!

**Comment by neowit** [comment]
Thanks.

in case if you consistently get wrong line count please try to come up with an example code which you can share and a step-by-step description allowing to reproduce the problem.
Otherwise there is not much can be done unfortunately.
