### ISSUE TITLE
sfdx support

### ISSUE THREAD

**Issue by zefreak** [neowit/vim-force.com#93]
I don't know where the correct place to ask this is, but is support planned for sfdx changes? pushing/deploying to scratch orgs (no credentials / security tokens), changes in project directory etc.

**Comment by neowit** [comment]
Do you have some`vim` specific examples in mind, showing how incorporating those functions in `vim` plugin might be useful?
As far as I understand `Salesforce DX CLI` can be called from inside and outside of `vim` as it is without any extra support from vim plugin.
