### ISSUE TITLE
Is there an option for force refresh of file. ApexRefreshFile doesn't support "!" like ApexDeploy! ?

### ISSUE THREAD

**Issue by asknet** [neowit/vim-force.com#95]
Is there an option for force refresh of file. ApexRefreshFile doesn't support "!" like ApexDeploy! ?

**Comment by neowit** [comment]
`: ApexRefreshFile` always does "force" refresh.

If your vim buffer does not get updated after `: ApexRefreshFile` is completed then you need to check your `vim` settings regarding what to do when file is updated externally (outside vim).
Specifically you may want to take a look at `:help autoread`

**Comment by asknet** [comment]
Thanks for the answer. Closing this
