### ISSUE TITLE
Is ApexTListToggle deprecated?

### ISSUE THREAD

**Issue by asknet** [neowit/vim-force.com#96]
Hi,
I'm exploring available commands and see this command doesn't exist, but present in documentation.

Thanks for wonderful plugin.

**Comment by neowit** [comment]
It is not deprecated but ":ApexTListToggle" only gets defined if [TagList](http://vim-taglist.sourceforge.net/) plugin is installed.
Although I personally have not used this plugin for ages, so I am not 100% sure if it still works. Give it a try if you want and let me know.

Having said that - you may want to consider using [Tagbar](http://majutsushi.github.io/tagbar/) instead.

**Comment by asknet** [comment]
Thanks. I'm already using Tagbar.
