### ISSUE TITLE
LWC support (in non-sfdx projects)

### ISSUE THREAD

**Issue by RetekBacsi** [neowit/vim-force.com#99]
Hi Neowit, 

this might be a config issue on my end, but vim-force.com doesn't seem to work well with lwc.
1. there is no LightningDefinitionBundle option on the ApexRetrieve screen
2. even if I manually add to the package.xml or create new LWC components with the plug-in it won't upload. The ApexDeploy commands fails with lwc being unknown component type.

Any help appreciated, thanks.

**Comment by neowit** [comment]
Hello @RetekBacsi 

This is most likely related to the fact that I have not published `tooling-force.com.jar` updated to support LWC. I am still testing it.
if you want to give it a go please let me know and I will share current dev version of the jar.

**Comment by RetekBacsi** [comment]
Hello @neowit,

I'd love to test the new version of tooling-force.com.jar. I already checked it out a few days ago, but couldn't compile it because of missing dependencies...

**Comment by neowit** [comment]
try downloading this file: https://www.dropbox.com/s/h8dfhnr75qc9j34/tooling-force.com-assembly-0.4.7.0-SNAPSHOT.jar?dl=1

**Comment by RetekBacsi** [comment]
Thank you, I successfully downloaded the file, set it as default version, and it seems to be working without issues as far as I can tell from 15 minutes of use...

**Comment by neowit** [comment]
closing as the issue was solved in v0.4.7.0
